let products=window.FITARO_PRODUCTS||[],selected;
const $=x=>document.getElementById(x);
async function init(){selected=products[0];render();if(location.protocol==="file:"){err("أنت فاتح الصفحة من الجهاز مباشرة. التصميم والمنتجات يعملان، لكن الذكاء الاصطناعي يحتاج رابط Vercel لأن /api لا يعمل من file://.");}}
function render(){$("suits").innerHTML=products.map(p=>`<article class="suit ${p.id===selected.id?"active":""}" data-id="${p.id}"><img src="${location.protocol==="file:" ? "public"+p.image : p.image}"><b>${p.name}</b><small>${p.fit}</small></article>`).join("");document.querySelectorAll(".suit").forEach(e=>e.onclick=()=>{selected=products.find(p=>p.id===e.dataset.id);render()})}
$("person").onchange=e=>{let f=e.target.files[0];if(f){$("preview").src=URL.createObjectURL(f);$("preview").style.display="block"}};
function err(t){$("error").textContent=t;$("error").classList.remove("hidden")}
function clear(){ $("error").classList.add("hidden") }
$("recommend").onclick=async()=>{clear();try{let r=await fetch("api/recommend",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gender:$("gender").value,height:+$("height").value,weight:+$("weight").value,occasion:$("occasion").value,products})});let d=await r.json();if(!r.ok)throw Error(d.error);$("rec").innerHTML=`<b>${d.headline}</b><br>المقاس: <strong>${d.size}</strong> — ${d.fit}<br>${d.text}`;$("rec").classList.remove("hidden")}catch(e){err(e.message)}};
async function tryon(){clear();let f=$("person").files[0];if(!f)return err("ارفع صورة الشخص أولاً.");$("loading").classList.remove("hidden");$("empty").classList.add("hidden");$("result").classList.add("hidden");$("again").classList.add("hidden");$("tryon").disabled=true;try{let b=await resize(f);let fd=new FormData();fd.append("personImage",b,"person.jpg");fd.append("suitId",selected.id);let r=await fetch("api/tryon",{method:"POST",body:fd});let d=await r.json();if(!r.ok||!d.success)throw Error(d.error);$("result").src=d.imageUrl;$("result").classList.remove("hidden");$("again").classList.remove("hidden")}catch(e){err(e.message);$("empty").classList.remove("hidden")}finally{$("loading").classList.add("hidden");$("tryon").disabled=false}}
function resize(file){return new Promise((ok,no)=>{let i=new Image(),u=URL.createObjectURL(file);i.onload=()=>{let s=Math.min(1,1600/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=i.width*s;c.height=i.height*s;c.getContext("2d").drawImage(i,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);b?ok(b):no(Error("تعذر تجهيز الصورة"))},"image/jpeg",.82)};i.onerror=()=>no(Error("الصورة غير صالحة"));i.src=u})}
$("tryon").onclick=tryon;$("again").onclick=tryon;
$("send").onclick=async()=>{let q=$("question").value.trim();if(!q)return;$("messages").innerHTML+=`<div class="bubble user">${esc(q)}</div>`;$("question").value="";try{let ms=[...document.querySelectorAll("#messages .bubble")].map(b=>({role:b.classList.contains("user")?"user":"assistant",content:b.textContent}));let r=await fetch("api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:ms,products})});let d=await r.json();if(!r.ok)throw Error(d.error);$("messages").innerHTML+=`<div class="bubble ai">${esc(d.text)}</div>`}catch(e){$("messages").innerHTML+=`<div class="bubble ai">حصلت مشكلة: ${esc(e.message)}</div>`}};
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}init();